#### 1.1 Creating a vector

In [1]:
import numpy as np

# Create vector as a row
vector_row = np.array([1,2,3])
print(vector_row)

# Create vector as a column
vector_col = np.array([[1],[2],[3]])
print(vector_col)

[1 2 3]
[[1]
 [2]
 [3]]


#### 1.2 Creating a Matrix

In [5]:
import numpy as np

matrix = np.array([[1, 2], [1, 2], [1, 2]])

#### 1.3 Creating a sparse Matrix

##### sparse matrix will only store the non-zero elements & assume all other values will be zero. Here below CSR means Compressed sparse row matrix

In [1]:
import numpy as np
from scipy import sparse

matrix = np.array([[0,0],[0,1],[3,0]])

matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [4]:
# Now let's create a larger matrix
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,1,0,0,0,0,0,0,0,0],
                        [3,0,0,0,0,0,0,0,0,0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(matrix_sparse)

print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


#### 1.4 Selecting elements

In [ ]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

matrix = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

# Select third element of the vector
vector[2]

np.int64(5)

In [12]:
# Select second row, second column
matrix[1,1]

np.int64(5)

##### numpy arrays are zero-indexed. Numpy allows variety of methods for selecting (indexing and slicing) elements or groups of elements in arrays.

In [14]:
# Select all elements of the vector
vector[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# From start to 3
vector[:3]

array([1, 2, 3])

In [16]:
# From 3 to end 
vector[3:]

array([4, 5, 6, 7, 8, 9])

In [17]:
# Select the last element 
vector[-1]

np.int64(9)

In [20]:
# Select 1st 2 rows and all columns of the matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Select all rows and 2nd column of the matrix
matrix[:,1:2]

array([[2],
       [5],
       [8]])

#### 1.5 Describing a Matrix

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

# View number of rows and columns
matrix.shape

12

In [3]:
# View number of elements (rows * columns)
matrix.size

12

In [5]:
matrix.ndim # [1,2,3]-> 1D && [[1, 2], [3, 4]] -> 2D and [[[1]]] -> 3D

2