#### 1.1 Creating a vector

In [1]:
import numpy as np

# Create vector as a row
vector_row = np.array([1,2,3])
print(vector_row)

# Create vector as a column
vector_col = np.array([[1],[2],[3]])
print(vector_col)

[1 2 3]
[[1]
 [2]
 [3]]


#### 1.2 Creating a Matrix

In [5]:
import numpy as np

matrix = np.array([[1, 2], [1, 2], [1, 2]])

#### 1.3 Creating a sparse Matrix

##### sparse matrix will only store the non-zero elements & assume all other values will be zero. Here below CSR means Compressed sparse row matrix

In [1]:
import numpy as np
from scipy import sparse

matrix = np.array([[0,0],[0,1],[3,0]])

matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


In [4]:
# Now let's create a larger matrix
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,1,0,0,0,0,0,0,0,0],
                        [3,0,0,0,0,0,0,0,0,0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(matrix_sparse)

print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


#### 1.4 Selecting elements

In [ ]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

matrix = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

# Select third element of the vector
vector[2]

np.int64(5)

In [12]:
# Select second row, second column
matrix[1,1]

np.int64(5)

##### numpy arrays are zero-indexed. Numpy allows variety of methods for selecting (indexing and slicing) elements or groups of elements in arrays.

In [14]:
# Select all elements of the vector
vector[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# From start to 3
vector[:3]

array([1, 2, 3])

In [16]:
# From 3 to end 
vector[3:]

array([4, 5, 6, 7, 8, 9])

In [17]:
# Select the last element 
vector[-1]

np.int64(9)

In [20]:
# Select 1st 2 rows and all columns of the matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# Select all rows and 2nd column of the matrix
matrix[:,1:2]

array([[2],
       [5],
       [8]])

#### 1.5 Describing a Matrix

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

# View number of rows and columns
matrix.shape

12

In [3]:
# View number of elements (rows * columns)
matrix.size

12

In [5]:
matrix.ndim # [1,2,3]-> 1D && [[1, 2], [3, 4]] -> 2D and [[[1]]] -> 3D

2

#### 1.6 Applying Operations to Elements

##### I want to apply function to multiple elements in an array

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create function that adds 100
add_100 = lambda i: i  + 100

# Create vectorized function 
vectorized_add_100 = np.vectorize(add_100) # This takes my function and creates a version that can be applied to every element of an array

result = vectorized_add_100(matrix) # Apply function to all elements

print(result)  # numpys vectorize class converts a function into a function that can be applied to all elements in an array or slice of an array
# vectorize is essentially a for loop over the elements and does not  increase 

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [10]:
# Numpy allow us to to perform operations between arrays even if their dimensions are not same (Broadcasting)
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

#### 1.7 Finding Max and Min Values

In [8]:
import numpy as np

matrix = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

# Returns maximum element
np.max(matrix)

np.int64(9)

In [9]:
# Returns minimum element
np.min(matrix)

np.int64(1)

In [12]:
# Using the axis parameter we can also apply the operation along a certain axis:
# Find maximum element in each column
np.max(matrix, axis = 0)

array([7, 8, 9])

In [13]:
# Find maximum element in each row
np.max(matrix, axis = 1)

array([3, 6, 9])

#### 1.8 Calculating the Average, Variance, and Standard Deviation

In [17]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Return mean
np.mean(matrix) # Here we are giving matrix to numpy's mean function

np.float64(5.0)

In [18]:
matrix.mean() # This is a method 

np.float64(5.0)

In [22]:
# Python list doesn't have a .mean() method
numbers = [1, 2, 3]
numbers.mean() 

AttributeError: 'list' object has no attribute 'mean'

In [23]:
# Return variance 
np.var(matrix)

np.float64(6.666666666666667)

In [24]:
# Return standard deviation
np.std(matrix)

np.float64(2.581988897471611)

#### 1.9 Reshaping arrays

In [26]:
# You want to change the shape(number of rows and columns) of an array without changing the element values
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [27]:
# One useful argument in reshape is -1, which effectively means "as many as needed"
matrix.reshape(1,-1) # One row and as many columns as needed

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [34]:
# If we provide one integer, reshape will return a 1D array of that length:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### 1.10 Transposing a matrix

In [38]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
# Vector cannot be transposed because it is a collection of values
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [41]:
# However it is common to refer to transposing a vector as converting a row vector to a column vector
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

#### 1.11 Flattening a Matrix

In [44]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# Flatten is a simple method to transform a matrix into a 1D array. Alternatively we can use reshape to create a row vector
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

#### 1.12 Finding the Rank of a Matrix

In [46]:
import numpy as np

matrix = np.array([[1, 1, 1], [1, 1, 10], [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

np.int64(2)

#### 1.13 Calculating the Determinant

In [48]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Return determinant of  matrix
np.linalg.det(matrix)

np.float64(0.0)

#### 1.14 Getting the Diagonal of a Matrix

In [50]:
import numpy as np

matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [51]:
# It is also possible to get a diagonal off from the main diagonal by using the offset parameter
# Return diagonal one above the main diagonal 
matrix.diagonal(offset = 1)

array([2, 6])

In [54]:
# Return diagonal one below the main diagonal 
matrix.diagonal(offset = -1)

array([2, 8])

#### 1.15 Calculating the trace of a Matrix

In [1]:
import numpy as np

matrix = np.array([[1, 2, 3],[2, 4, 6], [3, 8, 9]])

matrix.trace()

np.int64(14)

In [2]:
# We can also calculate the trace of the matrix using diagonal 
sum(matrix.diagonal())

np.int64(14)

#### 1.16 Finding Eigen values and Eigen vectors 

In [3]:
import numpy as np

matrix = np.array([[1, -1, 3], [1, 1, 6], [3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# View eigenvalues
eigenvalues


array([13.55075847,  0.74003145, -3.29078992])

In [4]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

#### 1.17 Calculating Dot Products


In [5]:
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate the dot product
np.dot(vector_a, vector_b)

np.int64(32)

In [6]:
# Alternatively in Python 3.5+ we can also calculate the dot product using @ operator:
vector_a @ vector_b

np.int64(32)

#### 1.18 Adding and Subtracting Matrices

In [10]:
import numpy as np

matrix_a = np.array([[1, 1, 1],[1, 1, 1],[1, 1, 2]])
matrix_b = np.array([[1, 3, 1],[1, 3, 1],[1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [11]:
# Subtract two matrices
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [12]:
# Alternatively we can simply use the + and - operators
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

#### 1.19 Multiplying Matrices

In [14]:
import numpy as np

matrix_a = np.array([[1, 1], [1, 2]])

matrix_b = np.array([[1, 3], [1, 2]])

np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [15]:
# Alternatively in Python we can use @ operator
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

#### 1.20 Inverting a matrix

In [17]:
import numpy as np

# Create matrix
matrix = np.array([[1, 4],[2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [19]:
# Multiply matrix and its inverse
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

#### 1.21 Generating Random Values

In [20]:
# You want to generate random values

import numpy as np

# Set seed
np.random.seed(0)

# Generate 3 random floats between 0 and 1
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [23]:
# Generate 3 random integers between 1 and 10
np.random.randint(0,11,3)

array([2, 4, 7], dtype=int32)

In [24]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0,1.0,3)

array([ 1.26611853, -0.50587654,  2.54520078])

In [26]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0,1.0,3)

array([-3.88073674,  1.60430957,  1.25495694])

In [27]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0,2.0,3)

array([1.87001215, 1.97861834, 1.79915856])